name: build-and-test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.1
        with:
          distribution: 'temurin'
          java-version: '20'


      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.4.0

      - run: make -C app build

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          coverageCommand: make -C app report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco

#name: Java CI

#on:
 # - push
 # - pull_request

#jobs:
#  build:
 #   runs-on: ubuntu-latest

#    steps:
 #     - uses: actions/checkout@v3
  #    - uses: actions/setup-java@v3
 #       with:
 #         java-version: '20'
 #         distribution: 'temurin'
 #     - uses: gradle/gradle-build-action@v2
#        with:
  #        gradle-version: 8.5
     # - run: ./gradlew checkstyleMain
 #     - run: ./app/gradlew checkstyleMain
      #- run: ./gradlew test
 #     - run: ./gradlew test
      # - name: Publish code coverage
      #   uses: paambaati/codeclimate-action@v5.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #     JACOCO_SOURCE_PATH: src/main/java
      #   with:
      #     coverageCommand: make report
      #     coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco